- name: app setup
  ansible.builtin.import_role:
     name: common
     tasks_from: app_setup.yaml
 
- name: python setup
  ansible.builtin.import_role:
     name: common
     tasks_from: python_setup.yaml

 
- name: systemd setup
  ansible.builtin.import_role:
     name: common
     tasks_from: systemd_setup.yaml

- name: enable and start user
  ansible.builtin.service:
      name: payment
      state: restarted
      enabled: yes
     
